### ISSUE TITLE
Quantum Composer Control - timeout

### ISSUE THREAD

**Issue by BradSchoenrock** [NCAR/WVD-MCSupdate#159]
When trying to set the state of the quantum composer one of several bugs have been short circuited. 

This one is a timeout error, that occurs no matter how high you set your timeout variable located in the Initialize function. 

----------------------------------------------

Error -1073807339 occurred at VISA Read in Quantum Composers 9000 Series.lvlib:Utility Write to Instrument.vi->Quantum Composers 9000 Series.lvlib:System Options.vi->Quantum Composers 9000 Series.lvlib:Close.vi->Quantum Composers 9000 Series Recall-Save Configuration.vi

Possible reason(s):

VISA:  (Hex 0xBFFF0015) Timeout expired before operation completed.

------------------------------------------------

Good luck future me? 

#21

**Comment by stillwer** [comment]
Brad noted that the command that was the problem was: Command/Query Sent:*IDN?. This is a clue that the hardware is not set up properly. I will document the procedure to do so for the future. 

The main issue here is that the quantum composer software asks the hardware to identify itself to figure out what features are available. This is done first and needs to be done. Without a response, the software falls on its face. No response will be forthcoming if the port is not set up correctly. 

The system has to be set up in combination with the router and the software that comes with the hardware before the labview will run. The failure of the *IDN? command is indicative of that. 

The error here is a response to the other error with the system not responding! Need to talk before its response can be heard.
