### ISSUE TITLE
Quantum Composer Control - Reference Not Found: 

### ISSUE THREAD

**Issue by BradSchoenrock** [NCAR/WVD-MCSupdate#165]
When trying to set the state of the quantum composer one of several bugs have been short circuited.

This one is Reference Not Found.

---------------------------

Error -1074003950 occurred at Utility Unit Info.vi

Possible reason(s):

Reference Not Found:  (xBFFC0012) Cannot retrieve user data for the given resource name as there was not data associated with the resource name.  Before you can read data, you need to write the user data using the Write Data action of this User Data VI. 

Complete call chain:
     Utility Unit Info.vi
     Instrument Info.vi
     Configure Sys (To) Input.vi
     Configure System Timer (To).vi
     Quantum Composers 9000 Series Recall-Save Configuration.vi
     ControlSystemQuantComp.vi

---------------------------

Good luck future me?
#21

**Comment by stillwer** [comment]
Brad noted that the command that was the problem was: Command/Query Sent:*IDN?. This is a clue that the hardware is not set up properly. I will document the procedure to do so for the future. 

The main issue here is that the quantum composer software asks the hardware to identify itself to figure out what features are available. This is done first and needs to be done. Without a response, the software falls on its face. No response will be forthcoming if the port is not set up correctly. 

The system has to be set up in combination with the router and the software that comes with the hardware before the labview will run. The failure of the *IDN? command is indicative of that.
