### ISSUE TITLE
DaqMX call evaluation 

### ISSUE THREAD

**Issue by BradSchoenrock** [NCAR/WVD-MCSupdate#99]
This is some time to check what the current functionality is before adding new features and checking if anything can be done in a more reliable or portable manner. Bare minimum DAQmx tasks should be modified.

**Comment by stillwer** [comment]
Turns out you can define DAQMx commands in the DAQMx program and bring over the commands as pre-defined entities or you can define them in the labview source code.  I created a new function in the laser locking library that creates the commands. Now instead of commands like Bristol or HSRLSwitch, you can do things like tell: "NI6000/port0/line0" to set their value. In this case there is no need to define the tasks externally. The function is called Ilde_GeneralDAQMxTaskExecuter.
